machines:
  x220:
    tmux:
      statusBg: "colour214 #dark orange"
      resurrectProcesses: 'btop "syncthing --no-browser" "journalctl -f" "gping -n 0.9 REDACTED-HOST REDACTED-IP REDACTED-IP REDACTED-IP"'
  x230:
    tmux:
      statusBg: "silver"
      resurrectProcesses: 'nvim btop "gping -n 0.8 REDACTED-HOST REDACTED-IP REDACTED-IP REDACTED-IP" "syncthing --no-browser" "mtr google.de" "./check_connection.sh"'
